apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
    tier: frontend
spec:
  selector:
    matchLabels:
      app: odoo
      tier: frontend
  strategy:
     type: RollingUpdate
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend
    spec:
      containers:
      - image: odoo
        name: odoo
        env:
        - name: HOST
          value: postgres-odoo #service mysql
        - name: USER
          value: aurelie
        - name: PASSWORD
          value: postgres
        volumeMounts:
        - name: odoo-web-data
          mountPath: /var/lib/odoo
        - name: odoo-config-storage
          mountPath: /etc/odoo
        - name: extra-addons-storage
          mountPath: /mnt/extra-addons
        ports:
        - containerPort: 8069
          name: odoo
      volumes:
      - name: odoo-web-data
        hostPath:
        # chemin du dossier sur l'hôte
          path: /data/odoo
      - name: extra-addons-storage
        hostPath:
          path: /data/addons
      - name: odoo-config-storage
        hostPath:
          path: /data/config
   

---

apiVersion: v1
kind: Service
metadata:
 name: odoo
 labels:
    app: odoo
    tier: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8069
    targetPort: 8069
    nodePort: 30080
  selector:
    app: odoo
    tier: frontend

